spring:
  application:
    name: online-store-service

server:
  port: 8080

logging:
  level:
    com:
      muratozgon:
        online:
          store:
            service:
              external=DEBUG:

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
feign:
  circuitbreaker:
    enabled: true

#resilience4j:
#  circuitbreaker:
#    configs:
#      default:
#        sliding-window-type: count_based
#        sliding-window-size: 5
#        failure-rate-threshold: 20
#        wait-duration-in-open-state: 5s
#        permitted-number-of-calls-in-half-open-state: 5

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: metrics, health, circuitbreakers, circuitbreakersevent

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true

